version: '3.8'
services:
  influxdb:
    container_name: influxdb
    image: influxdb:2.3.0-alpine
    ports:
      - 8087:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
      - DOCKER_INFLUXDB_INIT_RETENTION=365d
    volumes:
      - influxdb_volume:/var/lib/influxdb2

  redis:
    container_name: redis
    image: redis/redis-stack-server
    ports:
      - 6379:6379
    volumes:
      - redis_volume:/data

volumes:
  influxdb_volume:
  redis_volume:
